# Generated by Django 6.0.1 on 2026-02-01 15:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full company name', max_length=200, unique=True)),
                ('code', models.CharField(help_text="Short code (e.g., 'TCS', 'INFY')", max_length=20, unique=True)),
                ('description', models.TextField(help_text='Brief company overview')),
                ('website', models.URLField(blank=True, help_text='Company website')),
                ('headquarters', models.CharField(help_text='HQ location', max_length=200)),
                ('established_year', models.IntegerField(help_text='Year company was founded')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Skill name (e.g., 'Python', 'Django', 'MySQL')", max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Backend', 'Backend Development'), ('Frontend', 'Frontend Development'), ('Database', 'Database Management'), ('DevOps', 'DevOps & Infrastructure'), ('Mobile', 'Mobile Development'), ('Data', 'Data Science & Analytics'), ('SoftSkills', 'Soft Skills'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='What is this skill used for?')),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner Level'), ('Intermediate', 'Intermediate Level'), ('Advanced', 'Advanced Level')], default='Intermediate', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job position title', max_length=200)),
                ('description', models.TextField(help_text='Role responsibilities and requirements')),
                ('required_experience', models.IntegerField(choices=[(0, 'Fresher (0 years)'), (1, '1 year'), (2, '2 years'), (3, '3+ years')], help_text='Minimum experience required')),
                ('salary_range', models.CharField(help_text="Expected salary (e.g., '3.5-4.5 LPA')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company offering this role', on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='analyzer.company')),
            ],
            options={
                'verbose_name_plural': 'Job Roles',
                'ordering': ['company', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Resource title', max_length=300)),
                ('resource_type', models.CharField(choices=[('Video', 'Video Course'), ('Article', 'Article/Blog'), ('Course', 'Online Course'), ('Documentation', 'Official Documentation'), ('Book', 'Book/eBook'), ('Tutorial', 'Interactive Tutorial'), ('Other', 'Other')], help_text='Type of learning material', max_length=20)),
                ('url', models.URLField(help_text='Link to the resource')),
                ('description', models.TextField(blank=True, help_text='Brief description of what this resource covers')),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', help_text='Recommended difficulty level', max_length=15)),
                ('estimated_hours', models.IntegerField(help_text='Estimated time to complete (in hours)')),
                ('is_free', models.BooleanField(default=True, help_text='True if free, False if paid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(help_text='Skill this resource teaches', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='analyzer.skill')),
            ],
            options={
                'verbose_name_plural': 'Learning Resources',
                'ordering': ['-is_free', 'difficulty_level'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text="Student's contact number", max_length=15)),
                ('college_name', models.CharField(help_text='College/University name', max_length=200)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=10)),
                ('year', models.CharField(choices=[('FY', 'First Year'), ('SY', 'Second Year'), ('TY', 'Third Year'), ('FIN', 'Final Year')], max_length=5)),
                ('cgpa', models.FloatField(help_text='Cumulative GPA (0-10 scale)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_matched', models.IntegerField()),
                ('total_required_skills', models.IntegerField()),
                ('placement_readiness_percentage', models.FloatField()),
                ('analyzed_on', models.DateTimeField(auto_now_add=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.jobrole')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analyzer.studentprofile')),
            ],
            options={
                'verbose_name_plural': 'Skill Gap Analyses',
                'ordering': ['-analyzed_on'],
            },
        ),
        migrations.CreateModel(
            name='JobRoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('Basic', 'Basic Knowledge'), ('Intermediate', 'Intermediate Level'), ('Expert', 'Expert Level')], default='Intermediate', help_text='Required proficiency level for this role', max_length=15)),
                ('is_mandatory', models.BooleanField(default=True, help_text='True if must-have, False if nice-to-have')),
                ('job_role', models.ForeignKey(help_text='Job role this skill is required for', on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='analyzer.jobrole')),
                ('skill', models.ForeignKey(help_text='Required skill', on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='analyzer.skill')),
            ],
            options={
                'verbose_name_plural': 'Job Role Skills',
                'ordering': ['-is_mandatory', 'skill'],
                'unique_together': {('job_role', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('Basic', 'Basic Knowledge'), ('Intermediate', 'Intermediate Level'), ('Expert', 'Expert Level')], default='Intermediate', help_text="Student's current proficiency", max_length=15)),
                ('verified', models.BooleanField(default=False, help_text='Admin verified this skill')),
                ('added_on', models.DateTimeField(auto_now_add=True, help_text='When student added this skill')),
                ('skill', models.ForeignKey(help_text='Skill student has', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='analyzer.skill')),
                ('student', models.ForeignKey(help_text='Student who has this skill', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='analyzer.studentprofile')),
            ],
            options={
                'verbose_name_plural': 'Student Skills',
                'ordering': ['-verified', '-added_on'],
                'unique_together': {('student', 'skill')},
            },
        ),
    ]
